### ISSUE TITLE
Creates a couple of node process which end up slowing down my computer.

### ISSUE THREAD

**Issue by mathieuhays** [tableflip/nodebot-workshop#17]
Hi, 

I've been using this on my mac without connecting any Arduino. It started a couple of node process which has slowed down my mac.

At the moment I've got 4 node process, each one requesting an average of 88% of the CPU.
(went up to 15 process w/ an average of 20% cpu load). 

Doesn't make actual sense to me but maybe you guys will manage to fix that.
( I guess it's related to the Arduino simulation when you verify/run the exercises. )

Thanks.

**Comment by shennan** [comment]
I'm having the same issues. Having to kill node processes manually from the cli after every `verify` and `run` command.

**Comment by olizilla** [comment]
Thanks for reporting this @mathieuhays & @shennan, I can recreate the bug locally, and have a fix.

workshopper exec is spawning processes for the solution.js and the user provided file, but we never use them as we have to stub out firmata and manually verify the code ourselves. Seems those processes never clear up once the test is complete; as you work through the challenges you get 2 more orphan processes each time you verify. Removing the redundant exec call fixes it.
