### ISSUE TITLE
Challenge #8 - Fails using five.Temperature()

### ISSUE THREAD

**Issue by gyaresu** [tableflip/nodebot-workshop#23]
Solution shows using `five.Sensor('A0')` instead of `five.Temperature({...`

Is this a deprecation problem or am I just Doing It Wrong™?

Thanks for advice in advance :+1: 
```
var five = require('johnny-five')
var dnode = require('dnode')
var board = new five.Board()

board.on('ready', function () {

  var t = null
  
  var server = dnode({
    getTemperature: function (cb) {
      cb(t)
    }
  })

  server.listen(1337)

  var temp = new five.Temperature({
    controller: 'TMP36',
    pin: 'A0'
  })

  temp.on('data', function (err, data) {
    if (err) {
      console.error(err)
    }

    t = data.celsius
  })
})
```

**Comment by gyaresu** [comment]
My bad. I'm not used to the returned data being implicit like this.

The `Temperature` constructor works with the following:

```
temp.on('data', function () {
    t = this.celsius
  })
```
Time to update the exercise?

**Comment by achingbrain** [comment]
I think you were doing it right in the first place as it your solution doesn't depend on the internal state of the sensor and is consistent with the Temperature example in the Johnny-Five docs.

`board.Temperature` was added after this workshopper was written so you're right it just needs updating.

**Comment by achingbrain** [comment]
This has been updated..
