### ISSUE TITLE
Typo in exercise 1

### ISSUE THREAD

**Issue by ShadowManu** [tableflip/nodebot-workshop#27]
Close to the start of the problem description, it says 'Ardunio', instead of Arduino. Easy typo.

**Comment by castillobg** [comment]
This was fixed in https://github.com/tableflip/nodebot-workshop/commit/d8912da445841603f2a93b455c8d5b707ac11361 
Close it maybe?

**Comment by ShadowManu** [comment]
Oh, its in master but not in latest release (v2.2.6). Didn't catch that.
