### ISSUE TITLE
Exercise 4 - Fitzing diagram

### ISSUE THREAD

**Issue by DanBlakeman** [tableflip/nodebot-workshop#33]
I'm still learning so please forgive me if this is wrong.

But for me, this exercise works if the black cable coming from the button goes to 'Grnd', but in the diagram the black cable from the button goes to '5V'?

**Comment by gorhgorh** [comment]
good catch i'll fix this one asap )

**Comment by DanBlakeman** [comment]
Thanks @gorhgorh!!
