### ISSUE TITLE
Problems with the installation of nodebot-workshop

### ISSUE THREAD

**Issue by NervenCid** [tableflip/nodebot-workshop#36]
Hello:

I tried to install nodebot-workshop with the command:

npm install -g nodebot-workshop

but i get these instead:

```
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\nerve\AppData\Roaming\npm\node_modules\nodebot-workshop\nod
e_modules\weak\build\weakref.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\nodebot-workshop\node_modules\weak
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1
```

How can i solve this?

Thank you

**Comment by alanshaw** [comment]
Hiya, 

Looks like this is related to https://github.com/nodejs/node-gyp/issues/972.

Try installing Node.js v6.5.0 and then attempt to install nodebot-workshop again.

**Comment by NervenCid** [comment]
Hello @alanshaw , thank you for your answer:

I uninstalled nodejs and reinstalled nodejs 6.5.0 i tried again to install node bots but i got:

configure error
gyp ERR! stack Error: Python executable "C:\Anaconda3\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\nodebot-workshop\node_modules\weak
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1

**Comment by achingbrain** [comment]
From the error message it looks like the version of python you have installed is too recent for node-gyp to use.

You have 3.5.2 installed at `C:\Anaconda3\python.EXE` but it requires a version above 2.5.0 but below 3.0.0.

Can you please try installing an older version of python and updating your %PATH% variable to point to the older version first?

**Comment by NervenCid** [comment]
Thank you for your answer @achingbrain : i uninstalled python 3 and reinstalled Python 2 but i still getting this error when i try to install node bots:

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNot
ifyHook2': redefinition; different type modifiers [C:\Users\nerve\AppData\Roaming\npm\node_modules\nodebot-workshop\nod
e_modules\weak\build\weakref.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNot
  ifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nerve\AppData\Roaming\npm\node_modules\nodebot-workshop\node_modules\weak
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1
C:\Users\nerve\AppData\Roaming\npm
`-- nodebot-workshop@3.1.6

**Comment by achingbrain** [comment]
Could you make sure you have the latest versions of npm and node-gyp installed?  I think you need v3.4.0 or above of node-gyp and you've got v3.3.1.

```
npm -g install npm@latest
npm -g install node-gyp@latest
```

**Comment by NervenCid** [comment]
Thank you @achingbrain  for your answer, i tried and i solved the problem...

Thank you very much

**Comment by achingbrain** [comment]
Happy to help!
