### ISSUE TITLE
ERROR installing in windows

### ISSUE THREAD

**Issue by NervenCid** [tableflip/nodebot-workshop#40]
Hello, i trying to install in windows for node v6 and i get this error, how can i fix it?:

C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type mo
difiers [C:\Users\DiegoCamilo\AppData\Roaming\npm\node_modules\nodebot-workshop\node_modules\weak\build\weakref.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134): note: see declaration of '__pfnDliNotifyHook2'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\DiegoCamilo\AppData\Roaming\npm\node_modules\nodebot-workshop\node_modules\weak
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:weak@1.0.1 weak@1.0.1 install: `node-gyp rebuild`
npm WARN install:weak@1.0.1 Exit status 1

**Comment by achingbrain** [comment]
The version of npm has a buggy version of node-gyp. Can you please try:

npm install -g npm@latest

Then try installing the workshop again.

**Comment by NervenCid** [comment]
Thank you @achingbrain

**Comment by achingbrain** [comment]
No worries, please reopen this issue if you still have problems.
