### ISSUE TITLE
Arduino misspelled in a few places :-)

### ISSUE THREAD

**Issue by ruxandrafed** [tableflip/nodebot-workshop#43]
1. help.txt: https://github.com/tableflip/nodebot-workshop/blob/a1c7c887f6a85631ab4d3c5305a5052f49b9b790/help.txt#L10

2. package.json: https://github.com/tableflip/nodebot-workshop/blob/a1c7c887f6a85631ab4d3c5305a5052f49b9b790/package.json#L4

3. i18n/en.json: https://github.com/tableflip/nodebot-workshop/blob/a1c7c887f6a85631ab4d3c5305a5052f49b9b790/i18n/en.json#L3

**Comment by olizilla** [comment]
Thanks letting us know. Do you have a moment to send a PR to fix them?

**Comment by ruxandrafed** [comment]
@olizilla Sure! Here it is: https://github.com/tableflip/nodebot-workshop/pull/44. Thank you!
